module Reflex.Html.Elements.Html where

import Reflex.Html.Html
import Reflex.Html.Element
import Reflex.Html.DomString
import Reflex.Html.Render

import Reflex.Html.Prelude

html :: DomString -> ElementType
html = ElementType htmlNs

htmlNs :: DomString
htmlNs = "http://www.w3.org/1999/xhtml"

type MakeEl   = forall t a. Renderer t => [Property t] -> Html t a  -> Html t a
type MakeEl_  = forall t a. Renderer t => [Property t] -> Html t () -> Html t (Element t)
type MakeEl'  = forall t a. Renderer t => [Property t] -> Html t a  -> Html t (Element t, a)


html_head       = html "head"       :: ElementType
html_title      = html "title"      :: ElementType
html_base       = html "base"       :: ElementType
html_link       = html "link"       :: ElementType
html_meta       = html "meta"       :: ElementType
html_style      = html "style"      :: ElementType
html_script     = html "script"     :: ElementType
html_noscript   = html "noscript"   :: ElementType
html_body       = html "body"       :: ElementType
html_section    = html "section"    :: ElementType
html_nav        = html "nav"        :: ElementType
html_article    = html "article"    :: ElementType
html_aside      = html "aside"      :: ElementType
html_h1         = html "h1"         :: ElementType
html_h2         = html "h2"         :: ElementType
html_h3         = html "h3"         :: ElementType
html_h4         = html "h4"         :: ElementType
html_h5         = html "h5"         :: ElementType
html_h6         = html "h6"         :: ElementType
html_hgroup     = html "hgroup"     :: ElementType
html_header     = html "header"     :: ElementType
html_footer     = html "footer"     :: ElementType
html_address    = html "address"    :: ElementType
html_p          = html "p"          :: ElementType
html_hr         = html "hr"         :: ElementType
html_pre        = html "pre"        :: ElementType
html_blockquote = html "blockquote" :: ElementType
html_ol         = html "ol"         :: ElementType
html_ul         = html "ul"         :: ElementType
html_li         = html "li"         :: ElementType
html_dl         = html "dl"         :: ElementType
html_dt         = html "dt"         :: ElementType
html_dd         = html "dd"         :: ElementType
html_figure     = html "figure"     :: ElementType
html_figcaption = html "figcaption" :: ElementType
html_div        = html "div"        :: ElementType
html_a          = html "a"          :: ElementType
html_em         = html "em"         :: ElementType
html_strong     = html "strong"     :: ElementType
html_small      = html "small"      :: ElementType
html_s          = html "s"          :: ElementType
html_cite       = html "cite"       :: ElementType
html_q          = html "q"          :: ElementType
html_dfn        = html "dfn"        :: ElementType
html_abbr       = html "abbr"       :: ElementType
html_time       = html "time"       :: ElementType
html_code       = html "code"       :: ElementType
html_var        = html "var"        :: ElementType
html_samp       = html "samp"       :: ElementType
html_kbd        = html "kbd"        :: ElementType
html_sub        = html "sub"        :: ElementType
html_sup        = html "sup"        :: ElementType
html_i          = html "i"          :: ElementType
html_b          = html "b"          :: ElementType
html_u          = html "u"          :: ElementType
html_mark       = html "mark"       :: ElementType
html_ruby       = html "ruby"       :: ElementType
html_rt         = html "rt"         :: ElementType
html_rp         = html "rp"         :: ElementType
html_br         = html "br"         :: ElementType
html_bdi        = html "bdi"        :: ElementType
html_bdo        = html "bdo"        :: ElementType
html_span       = html "span"       :: ElementType
html_ins        = html "ins"        :: ElementType
html_del        = html "del"        :: ElementType
html_img        = html "img"        :: ElementType
html_iframe     = html "iframe"     :: ElementType
html_embed      = html "embed"      :: ElementType
html_object     = html "object"     :: ElementType
html_param      = html "param"      :: ElementType
html_video      = html "video"      :: ElementType
html_audio      = html "audio"      :: ElementType
html_source     = html "source"     :: ElementType
html_track      = html "track"      :: ElementType
html_canvas     = html "canvas"     :: ElementType
html_map        = html "map"        :: ElementType
html_area       = html "area"       :: ElementType
html_table      = html "table"      :: ElementType
html_caption    = html "caption"    :: ElementType
html_colgroup   = html "colgroup"   :: ElementType
html_col        = html "col"        :: ElementType
html_tbody      = html "tbody"      :: ElementType
html_thead      = html "thead"      :: ElementType
html_tfoot      = html "tfoot"      :: ElementType
html_tr         = html "tr"         :: ElementType
html_td         = html "td"         :: ElementType
html_th         = html "th"         :: ElementType
html_form       = html "form"       :: ElementType
html_fieldset   = html "fieldset"   :: ElementType
html_legend     = html "legend"     :: ElementType
html_label      = html "label"      :: ElementType
html_input      = html "input"      :: ElementType
html_button     = html "button"     :: ElementType
html_select     = html "select"     :: ElementType
html_datalist   = html "datalist"   :: ElementType
html_optgroup   = html "optgroup"   :: ElementType
html_option     = html "option"     :: ElementType
html_textarea   = html "textarea"   :: ElementType
html_keygen     = html "keygen"     :: ElementType
html_output     = html "output"     :: ElementType
html_progress   = html "progress"   :: ElementType
html_meter      = html "meter"      :: ElementType
html_details    = html "details"    :: ElementType
html_summary    = html "summary"    :: ElementType
html_command    = html "command"    :: ElementType
html_menu       = html "menu"       :: ElementType



head_       = el_ html_head         :: MakeEl_
--title_      = el_ html_title        :: MakeEl_
base_       = el_ html_base         :: MakeEl_
link_       = el_ html_link         :: MakeEl_
meta_       = el_ html_meta         :: MakeEl_
--style_      = el_ html_style        :: MakeEl_
script_     = el_ html_script       :: MakeEl_
noscript_   = el_ html_noscript     :: MakeEl_
body_       = el_ html_body         :: MakeEl_
section_    = el_ html_section      :: MakeEl_
nav_        = el_ html_nav          :: MakeEl_
article_    = el_ html_article      :: MakeEl_
aside_      = el_ html_aside        :: MakeEl_
h1_         = el_ html_h1           :: MakeEl_
h2_         = el_ html_h2           :: MakeEl_
h3_         = el_ html_h3           :: MakeEl_
h4_         = el_ html_h4           :: MakeEl_
h5_         = el_ html_h5           :: MakeEl_
h6_         = el_ html_h6           :: MakeEl_
hgroup_     = el_ html_hgroup       :: MakeEl_
header_     = el_ html_header       :: MakeEl_
footer_     = el_ html_footer       :: MakeEl_
address_    = el_ html_address      :: MakeEl_
p_          = el_ html_p            :: MakeEl_
pre_        = el_ html_pre          :: MakeEl_
blockquote_ = el_ html_blockquote   :: MakeEl_
ol_         = el_ html_ol           :: MakeEl_
ul_         = el_ html_ul           :: MakeEl_
li_         = el_ html_li           :: MakeEl_
dl_         = el_ html_dl           :: MakeEl_
dt_         = el_ html_dt           :: MakeEl_
dd_         = el_ html_dd           :: MakeEl_
figure_     = el_ html_figure       :: MakeEl_
figcaption_ = el_ html_figcaption   :: MakeEl_
div_        = el_ html_div          :: MakeEl_
a_          = el_ html_a            :: MakeEl_
em_         = el_ html_em           :: MakeEl_
strong_     = el_ html_strong       :: MakeEl_
small_      = el_ html_small        :: MakeEl_
s_          = el_ html_s            :: MakeEl_
--cite_       = el_ html_cite         :: MakeEl_
q_          = el_ html_q            :: MakeEl_
dfn_        = el_ html_dfn          :: MakeEl_
abbr_       = el_ html_abbr         :: MakeEl_
time_       = el_ html_time         :: MakeEl_
code_       = el_ html_code         :: MakeEl_
var_        = el_ html_var          :: MakeEl_
samp_       = el_ html_samp         :: MakeEl_
kbd_        = el_ html_kbd          :: MakeEl_
sub_        = el_ html_sub          :: MakeEl_
sup_        = el_ html_sup          :: MakeEl_
i_          = el_ html_i            :: MakeEl_
b_          = el_ html_b            :: MakeEl_
u_          = el_ html_u            :: MakeEl_
mark_       = el_ html_mark         :: MakeEl_
ruby_       = el_ html_ruby         :: MakeEl_
rt_         = el_ html_rt           :: MakeEl_
rp_         = el_ html_rp           :: MakeEl_
bdi_        = el_ html_bdi          :: MakeEl_
bdo_        = el_ html_bdo          :: MakeEl_
--span_       = el_ html_span         :: MakeEl_
ins_        = el_ html_ins          :: MakeEl_
del_        = el_ html_del          :: MakeEl_
img_        = el_ html_img          :: MakeEl_
iframe_     = el_ html_iframe       :: MakeEl_
embed_      = el_ html_embed        :: MakeEl_
object_     = el_ html_object       :: MakeEl_
param_      = el_ html_param        :: MakeEl_
video_      = el_ html_video        :: MakeEl_
audio_      = el_ html_audio        :: MakeEl_
source_     = el_ html_source       :: MakeEl_
track_      = el_ html_track        :: MakeEl_
canvas_     = el_ html_canvas       :: MakeEl_
map_        = el_ html_map          :: MakeEl_
area_       = el_ html_area         :: MakeEl_
table_      = el_ html_table        :: MakeEl_
caption_    = el_ html_caption      :: MakeEl_
colgroup_   = el_ html_colgroup     :: MakeEl_
col_        = el_ html_col          :: MakeEl_
tbody_      = el_ html_tbody        :: MakeEl_
thead_      = el_ html_thead        :: MakeEl_
tfoot_      = el_ html_tfoot        :: MakeEl_
tr_         = el_ html_tr           :: MakeEl_
td_         = el_ html_td           :: MakeEl_
th_         = el_ html_th           :: MakeEl_
--form_       = el_ html_form         :: MakeEl_
fieldset_   = el_ html_fieldset     :: MakeEl_
legend_     = el_ html_legend       :: MakeEl_
--label_      = el_ html_label        :: MakeEl_
input_      = el_ html_input        :: MakeEl_
button_     = el_ html_button       :: MakeEl_
select_     = el_ html_select       :: MakeEl_
datalist_   = el_ html_datalist     :: MakeEl_
optgroup_   = el_ html_optgroup     :: MakeEl_
option_     = el_ html_option       :: MakeEl_
textarea_   = el_ html_textarea     :: MakeEl_
keygen_     = el_ html_keygen       :: MakeEl_
output_     = el_ html_output       :: MakeEl_
progress_   = el_ html_progress     :: MakeEl_
meter_      = el_ html_meter        :: MakeEl_
details_    = el_ html_details      :: MakeEl_
--summary_    = el_ html_summary      :: MakeEl_
command_    = el_ html_command      :: MakeEl_
menu_       = el_ html_menu         :: MakeEl_



head'       = el' html_head         :: MakeEl'
title'      = el' html_title        :: MakeEl'
base'       = el' html_base         :: MakeEl'
link'       = el' html_link         :: MakeEl'
meta'       = el' html_meta         :: MakeEl'
style'      = el' html_style        :: MakeEl'
script'     = el' html_script       :: MakeEl'
noscript'   = el' html_noscript     :: MakeEl'
body'       = el' html_body         :: MakeEl'
section'    = el' html_section      :: MakeEl'
nav'        = el' html_nav          :: MakeEl'
article'    = el' html_article      :: MakeEl'
aside'      = el' html_aside        :: MakeEl'
h1'         = el' html_h1           :: MakeEl'
h2'         = el' html_h2           :: MakeEl'
h3'         = el' html_h3           :: MakeEl'
h4'         = el' html_h4           :: MakeEl'
h5'         = el' html_h5           :: MakeEl'
h6'         = el' html_h6           :: MakeEl'
hgroup'     = el' html_hgroup       :: MakeEl'
header'     = el' html_header       :: MakeEl'
footer'     = el' html_footer       :: MakeEl'
address'    = el' html_address      :: MakeEl'
p'          = el' html_p            :: MakeEl'
pre'        = el' html_pre          :: MakeEl'
blockquote' = el' html_blockquote   :: MakeEl'
ol'         = el' html_ol           :: MakeEl'
ul'         = el' html_ul           :: MakeEl'
li'         = el' html_li           :: MakeEl'
dl'         = el' html_dl           :: MakeEl'
dt'         = el' html_dt           :: MakeEl'
dd'         = el' html_dd           :: MakeEl'
figure'     = el' html_figure       :: MakeEl'
figcaption' = el' html_figcaption   :: MakeEl'
div'        = el' html_div          :: MakeEl'
a'          = el' html_a            :: MakeEl'
em'         = el' html_em           :: MakeEl'
strong'     = el' html_strong       :: MakeEl'
small'      = el' html_small        :: MakeEl'
s'          = el' html_s            :: MakeEl'
cite'       = el' html_cite         :: MakeEl'
q'          = el' html_q            :: MakeEl'
dfn'        = el' html_dfn          :: MakeEl'
abbr'       = el' html_abbr         :: MakeEl'
time'       = el' html_time         :: MakeEl'
code'       = el' html_code         :: MakeEl'
var'        = el' html_var          :: MakeEl'
samp'       = el' html_samp         :: MakeEl'
kbd'        = el' html_kbd          :: MakeEl'
sub'        = el' html_sub          :: MakeEl'
sup'        = el' html_sup          :: MakeEl'
i'          = el' html_i            :: MakeEl'
b'          = el' html_b            :: MakeEl'
u'          = el' html_u            :: MakeEl'
mark'       = el' html_mark         :: MakeEl'
ruby'       = el' html_ruby         :: MakeEl'
rt'         = el' html_rt           :: MakeEl'
rp'         = el' html_rp           :: MakeEl'
bdi'        = el' html_bdi          :: MakeEl'
bdo'        = el' html_bdo          :: MakeEl'
span'       = el' html_span         :: MakeEl'
ins'        = el' html_ins          :: MakeEl'
del'        = el' html_del          :: MakeEl'
img'        = el' html_img          :: MakeEl'
iframe'     = el' html_iframe       :: MakeEl'
embed'      = el' html_embed        :: MakeEl'
object'     = el' html_object       :: MakeEl'
param'      = el' html_param        :: MakeEl'
video'      = el' html_video        :: MakeEl'
audio'      = el' html_audio        :: MakeEl'
source'     = el' html_source       :: MakeEl'
track'      = el' html_track        :: MakeEl'
canvas'     = el' html_canvas       :: MakeEl'
map'        = el' html_map          :: MakeEl'
area'       = el' html_area         :: MakeEl'
table'      = el' html_table        :: MakeEl'
caption'    = el' html_caption      :: MakeEl'
colgroup'   = el' html_colgroup     :: MakeEl'
col'        = el' html_col          :: MakeEl'
tbody'      = el' html_tbody        :: MakeEl'
thead'      = el' html_thead        :: MakeEl'
tfoot'      = el' html_tfoot        :: MakeEl'
tr'         = el' html_tr           :: MakeEl'
td'         = el' html_td           :: MakeEl'
th'         = el' html_th           :: MakeEl'
form'       = el' html_form         :: MakeEl'
fieldset'   = el' html_fieldset     :: MakeEl'
legend'     = el' html_legend       :: MakeEl'
label'      = el' html_label        :: MakeEl'
input'      = el' html_input        :: MakeEl'
button'     = el' html_button       :: MakeEl'
select'     = el' html_select       :: MakeEl'
datalist'   = el' html_datalist     :: MakeEl'
optgroup'   = el' html_optgroup     :: MakeEl'
option'     = el' html_option       :: MakeEl'
textarea'   = el' html_textarea     :: MakeEl'
keygen'     = el' html_keygen       :: MakeEl'
output'     = el' html_output       :: MakeEl'
progress'   = el' html_progress     :: MakeEl'
meter'      = el' html_meter        :: MakeEl'
details'    = el' html_details      :: MakeEl'
summary'    = el' html_summary      :: MakeEl'
command'    = el' html_command      :: MakeEl'
menu'       = el' html_menu         :: MakeEl'



head       = el html_head           :: MakeEl
title      = el html_title          :: MakeEl
base       = el html_base           :: MakeEl
link       = el html_link           :: MakeEl
meta       = el html_meta           :: MakeEl
style      = el html_style          :: MakeEl
script     = el html_script         :: MakeEl
noscript   = el html_noscript       :: MakeEl
body       = el html_body           :: MakeEl
section    = el html_section        :: MakeEl
nav        = el html_nav            :: MakeEl
article    = el html_article        :: MakeEl
aside      = el html_aside          :: MakeEl
h1         = el html_h1             :: MakeEl
h2         = el html_h2             :: MakeEl
h3         = el html_h3             :: MakeEl
h4         = el html_h4             :: MakeEl
h5         = el html_h5             :: MakeEl
h6         = el html_h6             :: MakeEl
hgroup     = el html_hgroup         :: MakeEl
header     = el html_header         :: MakeEl
footer     = el html_footer         :: MakeEl
address    = el html_address        :: MakeEl
p          = el html_p              :: MakeEl
pre        = el html_pre            :: MakeEl
blockquote = el html_blockquote     :: MakeEl
ol         = el html_ol             :: MakeEl
ul         = el html_ul             :: MakeEl
li         = el html_li             :: MakeEl
dl         = el html_dl             :: MakeEl
dt         = el html_dt             :: MakeEl
dd         = el html_dd             :: MakeEl
figure     = el html_figure         :: MakeEl
figcaption = el html_figcaption     :: MakeEl
div        = el html_div            :: MakeEl
a          = el html_a              :: MakeEl
em         = el html_em             :: MakeEl
strong     = el html_strong         :: MakeEl
small      = el html_small          :: MakeEl
s          = el html_s              :: MakeEl
cite       = el html_cite           :: MakeEl
q          = el html_q              :: MakeEl
dfn        = el html_dfn            :: MakeEl
abbr       = el html_abbr           :: MakeEl
time       = el html_time           :: MakeEl
code       = el html_code           :: MakeEl
var        = el html_var            :: MakeEl
samp       = el html_samp           :: MakeEl
kbd        = el html_kbd            :: MakeEl
sub        = el html_sub            :: MakeEl
sup        = el html_sup            :: MakeEl
i          = el html_i              :: MakeEl
b          = el html_b              :: MakeEl
u          = el html_u              :: MakeEl
mark       = el html_mark           :: MakeEl
ruby       = el html_ruby           :: MakeEl
rt         = el html_rt             :: MakeEl
rp         = el html_rp             :: MakeEl
bdi        = el html_bdi            :: MakeEl
bdo        = el html_bdo            :: MakeEl
span       = el html_span           :: MakeEl
ins        = el html_ins            :: MakeEl
del        = el html_del            :: MakeEl
img        = el html_img            :: MakeEl
iframe     = el html_iframe         :: MakeEl
embed      = el html_embed          :: MakeEl
object     = el html_object         :: MakeEl
param      = el html_param          :: MakeEl
video      = el html_video          :: MakeEl
audio      = el html_audio          :: MakeEl
source     = el html_source         :: MakeEl
track      = el html_track          :: MakeEl
canvas     = el html_canvas         :: MakeEl
map        = el html_map            :: MakeEl
area       = el html_area           :: MakeEl
table      = el html_table          :: MakeEl
caption    = el html_caption        :: MakeEl
colgroup   = el html_colgroup       :: MakeEl
col        = el html_col            :: MakeEl
tbody      = el html_tbody          :: MakeEl
thead      = el html_thead          :: MakeEl
tfoot      = el html_tfoot          :: MakeEl
tr         = el html_tr             :: MakeEl
td         = el html_td             :: MakeEl
th         = el html_th             :: MakeEl
form       = el html_form           :: MakeEl
fieldset   = el html_fieldset       :: MakeEl
legend     = el html_legend         :: MakeEl
label      = el html_label          :: MakeEl
input      = el html_input          :: MakeEl
button     = el html_button         :: MakeEl
select     = el html_select         :: MakeEl
datalist   = el html_datalist       :: MakeEl
optgroup   = el html_optgroup       :: MakeEl
option     = el html_option         :: MakeEl
textarea   = el html_textarea       :: MakeEl
keygen     = el html_keygen         :: MakeEl
output     = el html_output         :: MakeEl
progress   = el html_progress       :: MakeEl
meter      = el html_meter          :: MakeEl
details    = el html_details        :: MakeEl
summary    = el html_summary        :: MakeEl
command    = el html_command        :: MakeEl
menu       = el html_menu           :: MakeEl


br ::  Renderer t => [Property t] -> Html t (Element t)
br attrs = el_ html_br attrs (return ())

hr :: Renderer t => [Property t] -> Html t (Element t)
hr attrs = el_ html_hr attrs (return ())


accept_          = commaListA "accept"               :: Attribute [DomString]
accept_charset_  = spaceListA "accept-charset"       :: Attribute [DomString]
accesskey_       = strA "accesskey"                  :: Attribute DomString
align_           = strA "align"                      :: Attribute DomString
action_          = strA "action"                     :: Attribute DomString
alt_             = strA "alt"                        :: Attribute DomString
async_           = boolA "async"                     :: Attribute Bool
autocomplete_    = boolA' "on" "off" "autocomplete"  :: Attribute Bool -- False = "off", True = "on"
autofocus_       = boolA "autofocus"                 :: Attribute Bool
autoplay_        = boolA "autoplay"                  :: Attribute Bool
autosave_        = boolA "autosave"                  :: Attribute Bool
border_          = boolA' "1" "" "border"            :: Attribute Bool   -- False = "", True = "1"
challenge_       = strA "challenge"                  :: Attribute DomString
charset_         = strA "charset"                    :: Attribute DomString
checked_         = boolA "checked"                   :: Attribute Bool
cite_            = strA "cite"                       :: Attribute DomString
class_           = spaceListA "class"                :: Attribute [DomString]
cols_            = intA "cols"                       :: Attribute Int
colspan_         = intA "colspan"                    :: Attribute Int
content_         = strA "content"                    :: Attribute DomString
contextmenu_     = strA "contextmenu"                :: Attribute DomString
controls_        = boolA "controls"                  :: Attribute Bool
coords_          = commaSep $ intA "coords"          :: Attribute [Int]
data_            = strA "data"                       :: Attribute DomString
datetime_        = strA "datetime"                   :: Attribute DomString
default_         = boolA "default"                   :: Attribute Bool
defer_           = boolA "defer"                     :: Attribute Bool
dir_             = strA "dir"                        :: Attribute DomString
dirname_         = strA "dirname"                    :: Attribute DomString
disabled_        = boolA "disabled"                  :: Attribute Bool
draggable_       = boolA' "true" "false" "draggable" :: Attribute Bool
dropzone_        = spaceListA "dropzone"             :: Attribute [DomString]
enctype_         = strA "enctype"                    :: Attribute DomString
for_             = strA "for"                        :: Attribute DomString
form_            = strA "form"                       :: Attribute DomString
formaction_      = strA "formaction"                 :: Attribute DomString
formnovalidate_  = boolA "formaction"                :: Attribute Bool
headers_         = spaceListA "headers"              :: Attribute [DomString]
height_          = intA "height"                     :: Attribute Int
hidden_          = boolA "hidden"                    :: Attribute Bool
high_            = floatA "high"                     :: Attribute Float
href_            = strA "href"                       :: Attribute DomString
hreflang_        = strA "hreflang"                   :: Attribute DomString
http_equiv       = strA "http-equiv"                 :: Attribute DomString
icon_            = strA "icon"                       :: Attribute DomString
id_              = strA "id"                         :: Attribute DomString
ismap_           = boolA "ismap"                     :: Attribute Bool
itemprop_        = strA "itemprop"                   :: Attribute DomString
keytype_         = strA "keytype"                    :: Attribute DomString
kind_            = strA "kind"                       :: Attribute DomString
label_           = strA "label"                      :: Attribute DomString
lang_            = strA "lang"                       :: Attribute DomString
list_            = strA "list"                       :: Attribute DomString
loop_            = boolA "loop"                      :: Attribute Bool
low_             = floatA "low"                      :: Attribute Float
manifest_        = strA "manifest"                   :: Attribute DomString
max_             = floatA "max"                      :: Attribute Float
maxlength_       = intA "maxlength"                  :: Attribute Int
media_           = strA "media"                      :: Attribute DomString
method_          = strA "method"                     :: Attribute DomString
min_             = floatA "min"                      :: Attribute Float
multiple_        = boolA "multiple"                  :: Attribute Bool
name_            = strA "name"                       :: Attribute DomString
novalidate_      = boolA "novalidate"                :: Attribute Bool
open_            = boolA "open"                      :: Attribute Bool
optimum_         = floatA "optimum"                  :: Attribute Float
pattern_         = strA "pattern"                    :: Attribute DomString
ping_            = strA "ping"                       :: Attribute DomString
placeholder_     = strA "placeholder"                :: Attribute DomString
poster_          = strA "poster"                     :: Attribute DomString
preload_         = strA "preload"                    :: Attribute DomString
radiogroup_      = strA "radiogroup"                 :: Attribute DomString
readonly_        = boolA "readonly"                  :: Attribute Bool
rel_             = spaceListA "rel"                  :: Attribute [DomString]
required_        = boolA "required"                  :: Attribute Bool
reversed_        = boolA "reversed"                  :: Attribute Bool
rows_            = intA "rows"                       :: Attribute Int
rowspan_         = intA "rowspan"                    :: Attribute Int
sandbox_         = spaceListA "sandbox"              :: Attribute [DomString]
scope_           = strA "scope"                      :: Attribute DomString
spellcheck_      = boolA' "true" "false" "scope"     :: Attribute Bool
scoped_          = boolA "scoped"                    :: Attribute Bool
seamless_        = boolA "seamless"                  :: Attribute Bool
selected_        = boolA "selected"                  :: Attribute Bool
shape_           = strA "shape"                      :: Attribute DomString
size_            = intA "size"                       :: Attribute Int
sizes_           = spaceListA "sizes"                :: Attribute [DomString]
span_            = intA "span"                       :: Attribute Int
src_             = strA "src"                        :: Attribute DomString
srcdoc_          = strA "srcdoc"                     :: Attribute DomString
srclang_         = strA "srclang"                    :: Attribute DomString
start_           = intA "start"                      :: Attribute Int
step_            = floatA "step"                     :: Attribute Float
style_           = strA "style"                      :: Attribute DomString
summary_         = strA "summary"                    :: Attribute DomString
tabindex_        = intA "tabindex"                   :: Attribute Int
target_          = strA "target"                     :: Attribute DomString
title_           = strA "title"                      :: Attribute DomString
type_            = strA "type"                       :: Attribute DomString
usemap_          = strA "usemap"                     :: Attribute DomString
value_           = strA "value"                      :: Attribute DomString
width_           = intA "width"                      :: Attribute Int
wrap_            = strA "wrap"                       :: Attribute DomString
